const USER_ANSWER_COOKIE_NAME = 'USER_ANSWER'
const START_TIMESTAMP_COOKIE_NAME = 'START_TIMESTAMP'
const END_TIMESTAMP_COOKIE_NAME = 'END_TIMESTAMP'

enum PATH {
  HOME = '/',
  QUIZ = '/quiz',
  RESULT = '/quiz/result',
  INCORRECT = '/quiz/incorrect',
}

export { USER_ANSWER_COOKIE_NAME, START_TIMESTAMP_COOKIE_NAME, END_TIMESTAMP_COOKIE_NAME, PATH }
